---
name: Basic workflow Demo running linux commands
on: 
  workflow_dispatch: 
jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - name: Run linux commands
        run: echo "Hello all"
  job2:
    runs-on: ubuntu-24.04
    steps: 
      - name: Run multiple linux commands
        run: |
          hostname -s 
          date
          pwd   
          ls -la
